
# packages
SDL2DIR		= SDL2-2.0.5
SDL2_TTFDIR	= SDL2_ttf-2.0.15
YASMDIR		= yasm-1.3.0
LAMEDIR		= lame-3.99.5
OPUSDIR		= opus-1.1
OGGDIR		= libogg-1.3.2
VORBISDIR	= libvorbis-1.3.5
THEORADIR	= libtheora-1.1.1
VPXDIR		= libvpx-1.4.0
X264DIR		= x264-snapshot-20151001-2245
X265DIR		= x265_1.9
XVIDDIR		= xvidcore-1.3.4
FFMPEGDIR	= ffmpeg-2.8.8
LIVE555DIR	= live

